//next
import Head from 'next/head'
import { useRouter } from 'next/router';
import Image from 'next/image';
import { NextPage } from "next";
//react
import { Fragment, useEffect } from 'react'

import ArrowBackIcon from '@mui/icons-material/ArrowBack';

//util
import { hasCookie, getCookie, } from 'cookies-next';

//redux
import { connect } from 'react-redux';
import { useDispatch } from 'react-redux';
import { updateHomeThemeName } from '@/redux/homeThemeName';
import { updateHomeThemeType } from '@/redux/homeThemeType';

import useScssVar from '@/hooks/useScssVar';
import { AppState } from '@/redux/store';

const Custom404: NextPage = (props: any) => {
  const router = useRouter()
  const errorCode = props.router.route.substring(1);
  const dispatch = useDispatch()
  const {
    secondaryMain,
    primaryMain,
    circleMain,
    circleOne,
    pieceOne,
    pieceTwo,
    pieceThree,
    threeOptionMain,
    textColor,
    muiVar
  } = useScssVar()

  useEffect(() => {
    if (typeof window !== 'undefined') {
      var scene = document.getElementById('scene');
      //@ts-ignore
      var parallax = new Parallax(scene);
    }
  }, [])

  useEffect(() => {
    if (hasCookie('homeThemeType')) {
      dispatch(updateHomeThemeType(getCookie('homeThemeType')))
    }
    if (hasCookie('homeThemeName')) {
      dispatch(updateHomeThemeName(getCookie('homeThemeName')))
    }
  }, [dispatch]);

  return (
    <Fragment>
      <Head>
        <title>404 Error</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="about">
        <a className="bg_links social portfolio" href="https://nastaransamui.github.io/" target="_blank">
          <span className="icon"
            style={secondaryMain}></span>
        </a>
        <a className="bg_links social dribbble" href="https://dribbble.com" target="_blank">
          <span className="icon" style={secondaryMain}></span>
        </a>
        <a className="bg_links social linkedin" href="https://www.linkedin.com" target="_blank">
          <span className="icon" style={secondaryMain}></span>
        </a>
        <a className="bg_links logo404" style={primaryMain}></a>
      </div>
      <nav>
        <div className="menu">
          <p className="website_name" onClick={() => {
            router.push('/', undefined, { shallow: true })
          }}><Image
              priority
              src="/assets/images/health_logo_clear.png"
              width={50}
              height={50}
              alt=""
            /></p>
          <div className="menu_links">
            {/* <a href="" className="link"
              style={threeOptionMain}>about</a>
            <a href="" className="link"
              style={threeOptionMain}>projects</a> */}
            <a href="" className="link"
              onClick={(e) => {
                e.preventDefault();
                router.back()
              }}
              style={threeOptionMain}>
              {/* <IconButton> */}
              <ArrowBackIcon />
              {/* </IconButton> */}
            </a>
          </div>
          <div className="menu_icon">
            <span className="icon"></span>
          </div>
        </div>
      </nav>
      <section className="wrapper" style={muiVar}>
        <div className="container">

          <div id="scene" className="scene" data-hover-only="false">


            <div className="circle" data-depth="1.2" style={circleMain}></div>

            <div className="one" data-depth="0.9" style={circleOne}>
              <div className="content">
                <span className="piece" style={pieceOne}></span>
                <span className="piece" style={pieceTwo}></span>
                <span className="piece" style={pieceThree}></span>
              </div>
            </div>

            <div className="two" data-depth="0.60">
              <div className="content">
                <span className="piece" style={threeOptionMain}></span>
                <span className="piece" style={threeOptionMain}></span>
                <span className="piece" style={threeOptionMain}></span>
              </div>
            </div>

            <div className="three" style={primaryMain} data-depth="0.40">
              <div className="content">
                <span className="piece"></span>
                <span className="piece"></span>
                <span className="piece"></span>
              </div>
            </div>

            <p className="p404" style={textColor} data-depth="0.50">{errorCode}</p>
            <p className="p404" style={textColor} data-depth="0.10">{errorCode}</p>

          </div>


          <div className="text">
            <article>
              <p>Uh oh Looks like you got lost. <br />Go back to the homepage</p>
              <button
                style={secondaryMain}
                onClick={() => {
                  router.push('/', undefined, { shallow: true })
                }}>Home</button>
            </article>
          </div>
        </div>
      </section>
    </Fragment>
  );
}


export default connect((state: AppState) => state)(Custom404);